// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Planning.Infrastructure;

#nullable disable

namespace Planning.Infrastructure.Migrations
{
    [DbContext(typeof(PlanningDbContext))]
    partial class PlanningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Planning.Domain.Entities.AiAssignmentCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<Guid>("CandidateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CandidateUserId")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("CandidateUserId"), "utf8mb4");

                    b.Property<decimal?>("CapacityScore")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("CapacityScore")
                        .HasComment("Còn dư capacity trong sprint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Explanation")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Explanation")
                        .HasComment("Câu giải thích hiển thị cho PM");

                    b.Property<string>("FeatureSnapshot")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("FeatureSnapshot")
                        .HasComment("TOÀN BỘ feature thô tại thời điểm chạy: open_points, in_progress_count, capacity, skill_levels, avg_cycle_time... KHÔNG ĐƯỢC tính lại khi train, nếu không sẽ data leakage");

                    b.Property<decimal?>("HistoryScore")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("HistoryScore")
                        .HasComment("Từng làm task tương tự (component/label) và làm tốt");

                    b.Property<bool>("IsColdStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsColdStart")
                        .HasComment("TRUE = user chưa có log task, điểm tính từ UserProfile/UserSkill thay vì lịch sử");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .HasComment("XMOD -> Issue.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<decimal?>("LoadBalanceScore")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("LoadBalanceScore")
                        .HasComment("Càng ít point đang gánh, điểm càng cao");

                    b.Property<int>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("Rank")
                        .HasComment("1 = gợi ý tốt nhất");

                    b.Property<Guid>("RunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("RunId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("RunId"), "utf8mb4");

                    b.Property<decimal?>("SkillMatchScore")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("SkillMatchScore")
                        .HasComment("Khớp IssueRequiredSkill với UserSkill");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("TotalScore");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IssueId", "Rank" }, "IX_AiAssignmentCandidate_Issue");

                    b.HasIndex(new[] { "RunId", "IssueId", "Rank" }, "IX_AiAssignmentCandidate_Run_Issue_Rank");

                    b.HasIndex(new[] { "RunId", "IssueId", "CandidateUserId" }, "UQ_AiAssignmentCandidate")
                        .IsUnique();

                    b.ToTable("AiAssignmentCandidate", null, t =>
                        {
                            t.HasComment("Mỗi (issue, user) một dòng có điểm - đây chính là format dữ liệu chuẩn cho learning-to-rank sau này");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.AiAssignmentDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<decimal?>("ActualCycleTimeHours")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("ActualCycleTimeHours");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DecidedAt");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("DecidedBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("DecidedBy"), "utf8mb4");

                    b.Property<Guid?>("FinalUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("FinalUserId")
                        .HasComment("XMOD -> User.Id. Người thực sự được gán")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("FinalUserId"), "utf8mb4");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .HasComment("XMOD -> Issue.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Outcome")
                        .HasComment("Pending / Accepted / Overridden / Rejected — NHÃN HUẤN LUYỆN");

                    b.Property<DateTime?>("OutcomeEvaluatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("OutcomeEvaluatedAt");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("OverrideReason")
                        .HasComment("PM ghi lý do đổi người - dữ liệu quý nhất để cải thiện model");

                    b.Property<Guid>("RunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("RunId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("RunId"), "utf8mb4");

                    b.Property<Guid?>("SuggestedCandidateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SuggestedCandidateId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("SuggestedCandidateId"), "utf8mb4");

                    b.Property<Guid?>("SuggestedUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SuggestedUserId")
                        .HasComment("XMOD -> User.Id. Ứng viên Rank = 1")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("SuggestedUserId"), "utf8mb4");

                    b.Property<bool?>("WasCompletedOnTime")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("WasCompletedOnTime");

                    b.Property<bool>("WasReassignedLater")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("WasReassignedLater")
                        .HasComment("Bị chuyển người sau đó = dấu hiệu gợi ý sai");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IssueId" }, "IX_AiAssignmentDecision_Issue");

                    b.HasIndex(new[] { "Outcome", "CreatedAt" }, "IX_AiAssignmentDecision_Outcome");

                    b.HasIndex(new[] { "RunId", "IssueId" }, "UQ_AiAssignmentDecision")
                        .IsUnique();

                    b.ToTable("AiAssignmentDecision", null, t =>
                        {
                            t.HasComment("Nhãn cho AI phân phối: PM có theo gợi ý không, và kết quả thực tế ra sao");

                            t.HasCheckConstraint("CK_AiAssignmentDecision_Outcome", "`Outcome` IN ('Pending','Accepted','Overridden','Rejected')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.AiAssignmentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("CandidateUserIds")
                        .HasColumnType("json")
                        .HasColumnName("CandidateUserIds")
                        .HasComment("Danh sách user được xét (thành viên project tại thời điểm chạy)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CompletedAt");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("ErrorMessage");

                    b.Property<int>("IssueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("IssueCount");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int")
                        .HasColumnName("LatencyMs");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ModelId")
                        .HasComment("NULL nếu dùng scoring function thuần")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ModelId"), "utf8mb4");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .HasComment("XMOD -> Project.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("RequestedBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("RequestedBy"), "utf8mb4");

                    b.Property<Guid?>("SourceGenerationLogId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SourceGenerationLogId")
                        .HasComment("XMOD -> AiGenerationLog.Id. Nối 2 AI với nhau")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("SourceGenerationLogId"), "utf8mb4");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SprintId")
                        .HasComment("XMOD -> Sprint.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("SprintId"), "utf8mb4");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Status")
                        .HasComment("Pending / Processing / Completed / Failed");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("WeightedScore")
                        .HasColumnName("Strategy")
                        .HasComment("WeightedScore (giai đoạn 1) / LearnedRanker (giai đoạn 2) / RoundRobin (baseline đối chứng)");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("TriggerSource")
                        .HasComment("Manual / AfterAiBreakdown / SprintPlanning - luồng \"AI phân phối task VỪA ĐƯỢC AI bóc tách\" dùng AfterAiBreakdown");

                    b.Property<string>("Weights")
                        .HasColumnType("json")
                        .HasColumnName("Weights")
                        .HasComment("Trọng số dùng cho lần chạy này, VD {\"load\":0.4,\"skill\":0.3,\"history\":0.2,\"capacity\":0.1} - lưu để tái lập");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProjectId", "CreatedAt" }, "IX_AiAssignmentRun_Project");

                    b.HasIndex(new[] { "SourceGenerationLogId" }, "IX_AiAssignmentRun_Source");

                    b.HasIndex(new[] { "Status", "CreatedAt" }, "IX_AiAssignmentRun_Status_Created");

                    b.HasIndex(new[] { "Strategy", "CreatedAt" }, "IX_AiAssignmentRun_Strategy_Created");

                    b.ToTable("AiAssignmentRun", null, t =>
                        {
                            t.HasComment("Một lần chạy phân phối cho một tập issue");

                            t.HasCheckConstraint("CK_AiAssignmentRun_Status", "`Status` IN ('Pending','Processing','Completed','Failed')");

                            t.HasCheckConstraint("CK_AiAssignmentRun_Strategy", "`Strategy` IN ('WeightedScore','LearnedRanker','RoundRobin','Hybrid')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDefault");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Type")
                        .HasComment("Scrum (gắn Sprint) hoặc Kanban (liên tục)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_Board_Name");

                    b.HasIndex(new[] { "ProjectId", "Name" }, "UQ_Board_Name")
                        .IsUnique();

                    b.ToTable("Board", null, t =>
                        {
                            t.HasComment("Một project có thể có nhiều board");

                            t.HasCheckConstraint("CK_Board_Type", "`Type` IN ('Scrum','Kanban')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.BoardColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("char(36)")
                        .HasColumnName("BoardId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("BoardId"), "utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Name")
                        .HasComment("Ghi đè tên hiển thị, NULL = lấy theo status");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("OrderIndex");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("StatusId")
                        .HasComment("Cột ánh xạ tới WorkflowStatus nào")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("StatusId"), "utf8mb4");

                    b.Property<int?>("WipLimit")
                        .HasColumnType("int")
                        .HasColumnName("WipLimit")
                        .HasComment("BỔ SUNG: Mục 5.5 yêu cầu WIP limit nhưng v2.0 không có chỗ lưu");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_BoardColumn_Name");

                    b.HasIndex(new[] { "BoardId", "OrderIndex" }, "IX_BoardColumn_Order");

                    b.HasIndex(new[] { "BoardId", "StatusId" }, "UQ_BoardColumn_Status")
                        .IsUnique();

                    b.ToTable("BoardColumn", null, t =>
                        {
                            t.HasComment("BỔ SUNG: cột board + giới hạn WIP");

                            t.HasCheckConstraint("CK_BoardColumn_Wip", "`WipLimit` IS NULL OR `WipLimit` > 0");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.IssueType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(7)")
                        .HasDefaultValue("#0052CC")
                        .HasColumnName("ColorHex");

                    b.Property<sbyte>("HierarchyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("HierarchyLevel")
                        .HasComment("2=Epic, 1=Story/Task/Bug, 0=Sub-task");

                    b.Property<string>("IconKey")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IconKey");

                    b.Property<bool>("IsSubtask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsSubtask")
                        .HasComment("Validate khi gán ParentId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Name")
                        .HasComment("Epic / Story / Task / Bug / Sub-task");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("OrderIndex");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_IssueType_Name");

                    b.HasIndex(new[] { "ProjectId", "OrderIndex" }, "IX_IssueType_Project_Order");

                    b.HasIndex(new[] { "ProjectId", "Name" }, "UQ_IssueType_Name")
                        .IsUnique();

                    b.ToTable("IssueType", null, t =>
                        {
                            t.HasComment("Loại issue cấu hình theo từng project");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("OwnerId")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("OwnerId"), "utf8mb4");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Slug")
                        .HasComment("URL-friendly, dùng cho subdomain/route");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NULL ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_Organization_Name");

                    b.HasIndex(new[] { "OwnerId" }, "IX_Organization_OwnerId");

                    b.HasIndex(new[] { "Slug" }, "UQ_Organization_Slug")
                        .IsUnique();

                    b.ToTable("Organization", null, t =>
                        {
                            t.HasComment("Workspace cấp cao nhất, tương đương Site trong Jira Cloud");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.Priority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(7)")
                        .HasDefaultValue("#6B778C")
                        .HasColumnName("ColorHex");

                    b.Property<string>("IconKey")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IconKey");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level")
                        .HasComment("1 = Highest ... 5 = Lowest");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .HasComment("SỬA: NULL = mức ưu tiên dùng chung toàn hệ thống; có giá trị = riêng project (khớp Mục 5.2)")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ProjectId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_Priority_Name");

                    b.HasIndex(new[] { "ProjectId", "Level" }, "IX_Priority_Project");

                    b.ToTable("Priority", null, t =>
                        {
                            t.HasComment("Mức độ ưu tiên");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsArchived");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("IssueCounter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("IssueCounter")
                        .HasComment("BỔ SUNG: bộ đếm sinh IssueNumber (PROJ-1, PROJ-2...)");

                    b.Property<Guid>("LeadUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("LeadUserId")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("LeadUserId"), "utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)")
                        .HasColumnName("OrgId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("OrgId"), "utf8mb4");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ProjectKey")
                        .HasComment("Mã viết tắt sinh issue key, VD \"PROJ\". `Key` là từ khóa MySQL nên đổi tên cột");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NULL ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name", "Description" }, "FT_Project_Search")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex(new[] { "LeadUserId" }, "IX_Project_LeadUserId");

                    b.HasIndex(new[] { "Name" }, "IX_Project_Name");

                    b.HasIndex(new[] { "OrgId", "IsDeleted", "IsArchived", "Name" }, "IX_Project_Org_Visible_Name");

                    b.HasIndex(new[] { "OrgId", "ProjectKey" }, "UQ_Project_Org_Key")
                        .IsUnique();

                    b.ToTable("Project", null, t =>
                        {
                            t.HasComment("Dự án - đơn vị chứa Sprint/Issue/Board/cấu hình workflow riêng");

                            t.HasCheckConstraint("CK_Project_Key_Format", "`ProjectKey` REGEXP '^[A-Z][A-Z0-9]{1,9}$'");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.ProjectComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("DefaultSkillId")
                        .HasColumnType("char(36)")
                        .HasColumnName("DefaultSkillId")
                        .HasComment("XMOD -> SkillCatalog.Id. AI ASSIGNMENT: skill mặc định của component")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("DefaultSkillId"), "utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<Guid?>("LeadUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("LeadUserId")
                        .HasComment("XMOD -> User.Id. Dùng auto-suggest assignee")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("LeadUserId"), "utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Name")
                        .HasComment("Backend API, Mobile App, Database...");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_ProjectComponent_Name");

                    b.HasIndex(new[] { "ProjectId", "Name" }, "UQ_ProjectComponent_Name")
                        .IsUnique();

                    b.ToTable("ProjectComponent", null, t =>
                        {
                            t.HasComment("Tương đương Components của Jira");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.ProjectVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsReleased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsReleased");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Name")
                        .HasComment("v1.2.0");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("ReleaseDate");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("StartDate");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_ProjectVersion_Name");

                    b.HasIndex(new[] { "IsReleased", "ReleaseDate" }, "IX_ProjectVersion_Release");

                    b.HasIndex(new[] { "ProjectId", "Name" }, "UQ_ProjectVersion_Name")
                        .IsUnique();

                    b.ToTable("ProjectVersion", null, t =>
                        {
                            t.HasComment("Tương đương Fix Version / Release của Jira");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<Guid?>("ActiveGuard")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("char(36)")
                        .HasColumnName("ActiveGuard")
                        .HasComputedColumnSql("IF(`Status` = 'Active', `ProjectId`, NULL)", true)
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ActiveGuard"), "utf8mb4");

                    b.Property<DateTime?>("ActualCompleteAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ActualCompleteAt");

                    b.Property<DateTime?>("ActualStartAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ActualStartAt")
                        .HasComment("Thời điểm bấm Start thật");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("EndDate");

                    b.Property<string>("Goal")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Goal")
                        .HasComment("Sprint Goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Name");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("OrderIndex");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .HasComment("XMOD -> Project.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("StartDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Planned")
                        .HasColumnName("Status")
                        .HasComment("Planned / Active / Completed");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NULL ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_Sprint_Name");

                    b.HasIndex(new[] { "ProjectId", "StartDate", "EndDate" }, "IX_Sprint_Project_Dates");

                    b.HasIndex(new[] { "ProjectId", "OrderIndex" }, "IX_Sprint_Project_Order");

                    b.HasIndex(new[] { "ProjectId", "Status" }, "IX_Sprint_Project_Status");

                    b.HasIndex(new[] { "Status", "EndDate" }, "IX_Sprint_Status_EndDate");

                    b.HasIndex(new[] { "ActiveGuard" }, "UQ_Sprint_OneActivePerProject")
                        .IsUnique();

                    b.ToTable("Sprint", null, t =>
                        {
                            t.HasComment("Chu kỳ Scrum. UNIQUE trên ActiveGuard ép ràng buộc 1 Sprint Active/Project");

                            t.HasCheckConstraint("CK_Sprint_Dates", "`EndDate` IS NULL OR `StartDate` IS NULL OR `EndDate` >= `StartDate`");

                            t.HasCheckConstraint("CK_Sprint_Status", "`Status` IN ('Planned','Active','Completed')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.SprintMemberCapacity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<decimal?>("AvailableHours")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("AvailableHours")
                        .HasComment("Trừ nghỉ phép, họp, on-call");

                    b.Property<decimal?>("CapacityPoints")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("CapacityPoints")
                        .HasComment("Số point tối đa nhận được trong sprint này");

                    b.Property<string>("Note")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Note");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SprintId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("SprintId"), "utf8mb4");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SprintId", "UserId" }, "UQ_SprintCapacity")
                        .IsUnique();

                    b.ToTable("SprintMemberCapacity", null, t =>
                        {
                            t.HasComment("BỔ SUNG - AI ASSIGNMENT: trần công suất từng người, tránh gán quá tải");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.SprintSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<decimal>("AddedPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("AddedPoints")
                        .HasComment("BỔ SUNG: scope change trong sprint");

                    b.Property<decimal>("CompletedPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("CompletedPoints")
                        .HasComment("BỔ SUNG");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("RemainingIssueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("RemainingIssueCount");

                    b.Property<decimal>("RemainingPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("RemainingPoints");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("SnapshotDate");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SprintId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("SprintId"), "utf8mb4");

                    b.Property<int>("TotalIssueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TotalIssueCount");

                    b.Property<decimal>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("TotalPoints")
                        .HasComment("BỔ SUNG: để vẽ được ideal line");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SprintId", "SnapshotDate" }, "UQ_SprintSnapshot_Day")
                        .IsUnique();

                    b.ToTable("SprintSnapshot", null, t =>
                        {
                            t.HasComment("Ảnh chụp hằng ngày cho Burndown - không thể tính on-the-fly");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.UserPerformanceMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<int>("AssignedIssueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("AssignedIssueCount");

                    b.Property<decimal?>("AvgCycleTimeHours")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("AvgCycleTimeHours")
                        .HasComment("Trung bình từ InProgress -> Done");

                    b.Property<DateTime>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CalculatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<decimal>("CommittedPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("CommittedPoints");

                    b.Property<int>("CompletedIssueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("CompletedIssueCount");

                    b.Property<decimal>("CompletedPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("CompletedPoints");

                    b.Property<decimal?>("EstimateAccuracyRatio")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("EstimateAccuracyRatio")
                        .HasComment("TimeSpent / OriginalEstimate");

                    b.Property<decimal?>("MedianCycleTimeHours")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("MedianCycleTimeHours")
                        .HasComment("Median chống ảnh hưởng của outlier tốt hơn Avg");

                    b.Property<decimal?>("OnTimeRatio")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("OnTimeRatio")
                        .HasComment("Tỉ lệ hoàn thành trước DueDate");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .HasComment("XMOD -> Project.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.Property<int>("ReopenedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ReopenedCount")
                        .HasComment("Proxy cho chất lượng công việc");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SprintId")
                        .HasComment("XMOD -> Sprint.Id. NULL = số liệu tổng toàn project")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("SprintId"), "utf8mb4");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProjectId", "PeriodEnd" }, "IX_UserPerfMetric_Project_Period");

                    b.HasIndex(new[] { "SprintId" }, "IX_UserPerfMetric_Sprint");

                    b.HasIndex(new[] { "UserId", "ProjectId", "PeriodStart", "PeriodEnd" }, "UQ_UserPerfMetric")
                        .IsUnique();

                    b.ToTable("UserPerformanceMetric", null, t =>
                        {
                            t.HasComment("Feature \"năng lực thực tế\" cho AI phân phối task");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.UserWorkloadSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<decimal?>("CapacityPoints")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("CapacityPoints")
                        .HasComment("Lấy từ SprintMemberCapacity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("InProgressCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("InProgressCount");

                    b.Property<decimal>("InProgressPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("InProgressPoints");

                    b.Property<int>("OpenIssueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("OpenIssueCount");

                    b.Property<decimal>("OpenPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("OpenPoints")
                        .HasComment("Tổng point chưa Done đang gánh");

                    b.Property<int>("OverdueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("OverdueCount");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .HasComment("XMOD -> Project.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("SnapshotDate");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SprintId")
                        .HasComment("XMOD -> Sprint.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("SprintId"), "utf8mb4");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.Property<decimal?>("UtilizationRatio")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("UtilizationRatio")
                        .HasComment("OpenPoints / CapacityPoints. > 1.0 = quá tải");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProjectId", "SnapshotDate" }, "IX_UserWorkload_Project_Date");

                    b.HasIndex(new[] { "SprintId", "SnapshotDate" }, "IX_UserWorkload_Sprint_Date");

                    b.HasIndex(new[] { "UserId", "ProjectId", "SnapshotDate" }, "UQ_UserWorkloadSnapshot")
                        .IsUnique();

                    b.ToTable("UserWorkloadSnapshot", null, t =>
                        {
                            t.HasComment("Hangfire job hằng ngày. Đây là feature \"độ cân bằng khối lượng công việc\" mà đề xuất nhắc tới");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.WorkflowStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Category")
                        .HasComment("ToDo / InProgress / Done - chuẩn hóa để tính báo cáo");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(7)")
                        .HasDefaultValue("#8993A4")
                        .HasColumnName("ColorHex");

                    b.Property<bool>("IsInitial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsInitial")
                        .HasComment("Trạng thái mặc định khi tạo issue mới");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Name");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("OrderIndex");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_WorkflowStatus_Name");

                    b.HasIndex(new[] { "ProjectId", "OrderIndex" }, "IX_WorkflowStatus_Project_Order");

                    b.HasIndex(new[] { "ProjectId", "Name" }, "UQ_WorkflowStatus_Name")
                        .IsUnique();

                    b.ToTable("WorkflowStatus", null, t =>
                        {
                            t.HasComment("Mỗi Project tự định nghĩa bộ trạng thái riêng");

                            t.HasCheckConstraint("CK_WorkflowStatus_Category", "`Category` IN ('ToDo','InProgress','Done')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<Guid>("FromStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("FromStatusId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("FromStatusId"), "utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Name")
                        .HasComment("Tên nút bấm hiển thị, VD \"Gửi review\"");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .HasComment("BỔ SUNG: thiếu trong bản v2.0. Không có cột này phải JOIN 2 lần mới validate được")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.Property<string>("RequiredPermissionCode")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("RequiredPermissionCode")
                        .HasComment("Chỉ role có quyền này mới được chuyển");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ToStatusId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ToStatusId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FromStatusId" }, "IX_WorkflowTransition_From");

                    b.HasIndex(new[] { "Name" }, "IX_WorkflowTransition_Name");

                    b.HasIndex(new[] { "ToStatusId" }, "IX_WorkflowTransition_To");

                    b.HasIndex(new[] { "ProjectId", "FromStatusId", "ToStatusId" }, "UQ_WorkflowTransition")
                        .IsUnique();

                    b.ToTable("WorkflowTransition", null, t =>
                        {
                            t.HasComment("Luật chuyển trạng thái hợp lệ - chặn kéo thẳng ToDo -> Done");

                            t.HasCheckConstraint("CK_WorkflowTransition_NotSelf", "`FromStatusId` <> `ToStatusId`");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("Planning.Domain.Entities.AiAssignmentCandidate", b =>
                {
                    b.HasOne("Planning.Domain.Entities.AiAssignmentRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AiAssignmentCandidate_Run");
                });

            modelBuilder.Entity("Planning.Domain.Entities.AiAssignmentDecision", b =>
                {
                    b.HasOne("Planning.Domain.Entities.AiAssignmentRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AiAssignmentDecision_Run");

                    b.HasOne("Planning.Domain.Entities.AiAssignmentCandidate", null)
                        .WithMany()
                        .HasForeignKey("SuggestedCandidateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AiAssignmentDecision_Candidate");
                });

            modelBuilder.Entity("Planning.Domain.Entities.Board", b =>
                {
                    b.HasOne("Planning.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Board_Project");
                });

            modelBuilder.Entity("Planning.Domain.Entities.BoardColumn", b =>
                {
                    b.HasOne("Planning.Domain.Entities.Board", null)
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BoardColumn_Board");

                    b.HasOne("Planning.Domain.Entities.WorkflowStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BoardColumn_Status");
                });

            modelBuilder.Entity("Planning.Domain.Entities.IssueType", b =>
                {
                    b.HasOne("Planning.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueType_Project");
                });

            modelBuilder.Entity("Planning.Domain.Entities.Priority", b =>
                {
                    b.HasOne("Planning.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Priority_Project");
                });

            modelBuilder.Entity("Planning.Domain.Entities.Project", b =>
                {
                    b.HasOne("Planning.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Project_Organization");
                });

            modelBuilder.Entity("Planning.Domain.Entities.ProjectComponent", b =>
                {
                    b.HasOne("Planning.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectComponent_Project");
                });

            modelBuilder.Entity("Planning.Domain.Entities.ProjectVersion", b =>
                {
                    b.HasOne("Planning.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectVersion_Project");
                });

            modelBuilder.Entity("Planning.Domain.Entities.SprintMemberCapacity", b =>
                {
                    b.HasOne("Planning.Domain.Entities.Sprint", null)
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SprintCapacity_Sprint");
                });

            modelBuilder.Entity("Planning.Domain.Entities.SprintSnapshot", b =>
                {
                    b.HasOne("Planning.Domain.Entities.Sprint", null)
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SprintSnapshot_Sprint");
                });

            modelBuilder.Entity("Planning.Domain.Entities.WorkflowStatus", b =>
                {
                    b.HasOne("Planning.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WorkflowStatus_Project");
                });

            modelBuilder.Entity("Planning.Domain.Entities.WorkflowTransition", b =>
                {
                    b.HasOne("Planning.Domain.Entities.WorkflowStatus", null)
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WorkflowTransition_From");

                    b.HasOne("Planning.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WorkflowTransition_Project");

                    b.HasOne("Planning.Domain.Entities.WorkflowStatus", null)
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_WorkflowTransition_To");
                });
#pragma warning restore 612, 618
        }
    }
}
