<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ProjectMgmt.Core\ProjectMgmt.Core.csproj" />
    <ProjectReference Include="..\ProjectMgmt.IdentityAccess.Contracts\ProjectMgmt.IdentityAccess.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
