<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ProjectMgmt.AiAssignment.Contracts\ProjectMgmt.AiAssignment.Contracts.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Core\ProjectMgmt.Core.csproj" />
    <ProjectReference Include="..\ProjectMgmt.IdentityAccess.Contracts\ProjectMgmt.IdentityAccess.Contracts.csproj" />
    <ProjectReference Include="..\ProjectMgmt.IssueTracking.Contracts\ProjectMgmt.IssueTracking.Contracts.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Notification.Contracts\ProjectMgmt.Notification.Contracts.csproj" />
    <ProjectReference Include="..\ProjectMgmt.ProjectManagement.Contracts\ProjectMgmt.ProjectManagement.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>
</Project>
