<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProjectMgmt.AiAssignment.Contracts\ProjectMgmt.AiAssignment.Contracts.csproj" />
    <ProjectReference Include="..\ProjectMgmt.AiAssist.Contracts\ProjectMgmt.AiAssist.Contracts.csproj" />
    <ProjectReference Include="..\ProjectMgmt.AiDataOps.Contracts\ProjectMgmt.AiDataOps.Contracts.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Core\ProjectMgmt.Core.csproj" />
    <ProjectReference Include="..\ProjectMgmt.IdentityAccess.Contracts\ProjectMgmt.IdentityAccess.Contracts.csproj" />
    <ProjectReference Include="..\ProjectMgmt.IssueTracking.Contracts\ProjectMgmt.IssueTracking.Contracts.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Notification.Contracts\ProjectMgmt.Notification.Contracts.csproj" />
    <ProjectReference Include="..\ProjectMgmt.ProjectManagement.Contracts\ProjectMgmt.ProjectManagement.Contracts.csproj" />
  </ItemGroup>
</Project>
