// <auto-generated />
using System;
using DeliveryIntelligence.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliveryIntelligence.Infrastructure.Migrations
{
    [DbContext(typeof(DeliveryIntelligenceDbContext))]
    [Migration("20260911191050_FinalizeDeliveryDatabaseObjects")]
    partial class FinalizeDeliveryDatabaseObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AcceptanceCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<Guid?>("AiGenerationLogId")
                        .HasColumnType("char(36)")
                        .HasColumnName("AiGenerationLogId")
                        .HasComment("XMOD: truy vết AC này do request AI nào sinh")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("AiGenerationLogId"), "utf8mb4");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content")
                        .HasComment("Given-When-Then hoặc gạch đầu dòng");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsMet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsMet");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .HasComment("SỬA: cho phép gắn mọi loại issue, không chỉ Story (ví dụ JSON ở Mục 5.9.8 sinh AC cho Sub-task)")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<DateTime?>("MetAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("MetAt");

                    b.Property<Guid?>("MetBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("MetBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("MetBy"), "utf8mb4");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("OrderIndex");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("Source")
                        .HasComment("AI / Manual - đánh giá độ tin cậy gợi ý AI");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NULL ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("WasEditedAfterAi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("WasEditedAfterAi")
                        .HasComment("BỔ SUNG: nhãn huấn luyện - AC do AI sinh có bị sửa không");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Content" }, "FT_AcceptanceCriteria_Content")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex(new[] { "IssueId", "OrderIndex" }, "IX_AcceptanceCriteria_Issue");

                    b.HasIndex(new[] { "Source", "CreatedAt" }, "IX_AcceptanceCriteria_Source");

                    b.ToTable("AcceptanceCriteria", null, t =>
                        {
                            t.HasComment("Tiêu chí nghiệm thu, tick được từng dòng cho Definition of Done");

                            t.HasCheckConstraint("CK_AcceptanceCriteria_Source", "`Source` IN ('AI','Manual')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Action")
                        .HasComment("Created / StatusChanged / AssigneeChanged / AiBreakdownApplied...");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Detail")
                        .HasColumnType("json")
                        .HasColumnName("Detail")
                        .HasComment("Payload đầy đủ dạng JSON, query được bằng JSON_EXTRACT");

                    b.Property<string>("FieldName")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("FieldName");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("NewValue");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("OldValue");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("User")
                        .HasColumnName("Source")
                        .HasComment("User / System / AI - phân biệt để báo cáo AI");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .HasComment("XMOD -> User.Id. NULL = do hệ thống/AI thực hiện")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("UserId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Action", "CreatedAt" }, "IX_ActivityLog_Action");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_ActivityLog_CreatedAt");

                    b.HasIndex(new[] { "IssueId", "CreatedAt" }, "IX_ActivityLog_Issue");

                    b.HasIndex(new[] { "Source", "CreatedAt" }, "IX_ActivityLog_Source_Created");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "IX_ActivityLog_User_Created");

                    b.ToTable("ActivityLog", null, t =>
                        {
                            t.HasComment("Nhật ký thay đổi tự động - sinh qua IActivityLogService");

                            t.HasCheckConstraint("CK_ActivityLog_Source", "`Source` IN ('User','System','AI')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiAssignmentAccuracy", b =>
                {
                    b.Property<decimal>("AcceptedCount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AvgCycleTimeHours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<long>("DecisionCount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OverriddenCount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ReassignedLaterCount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable((string)null);

                    b.ToView("vw_AiAssignmentAccuracy", (string)null);
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiBreakdownQuality", b =>
                {
                    b.Property<decimal?>("AvgEditDistance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AvgLatencyMs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<decimal>("EditedCount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("KeptCount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PromptTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("RejectedCount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("RequestCount")
                        .HasColumnType("bigint");

                    b.Property<long>("SuggestedTaskCount")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("vw_AiBreakdownQuality", (string)null);
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiDataCleaningRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("All")
                        .HasColumnName("AppliesTo")
                        .HasComment("Breakdown / Assignment / All");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Code");

                    b.Property<string>("Config")
                        .HasColumnType("json")
                        .HasColumnName("Config")
                        .HasComment("Regex, ngưỡng min/max, danh sách từ cấm...");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("RuleType")
                        .HasComment("SchemaValidation / PiiDetection / Deduplication / LengthCheck / LanguageCheck / Heuristic");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Warning")
                        .HasColumnName("Severity")
                        .HasComment("Info / Warning / Error (Error = tự động Reject)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_AiDataCleaningRule_Name");

                    b.HasIndex(new[] { "Code" }, "UQ_AiDataCleaningRule_Code")
                        .IsUnique();

                    b.ToTable("AiDataCleaningRule", null, t =>
                        {
                            t.HasComment("Rule làm sạch dạng cấu hình - không hard-code trong script Python");

                            t.HasCheckConstraint("CK_AiDataCleaningRule_Severity", "`Severity` IN ('Info','Warning','Error')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiDataQualityFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DetectedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("FieldPath")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("FieldPath")
                        .HasComment("VD: $.subTasks[0].acceptanceCriteria");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsResolved");

                    b.Property<string>("Message")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Message");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ResolvedAt");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("ResolvedBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ResolvedBy"), "utf8mb4");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("RuleId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("RuleId"), "utf8mb4");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SampleId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("SampleId"), "utf8mb4");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Severity");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IsResolved", "Severity", "DetectedAt" }, "IX_AiDataQualityFlag_Queue");

                    b.HasIndex(new[] { "RuleId" }, "IX_AiDataQualityFlag_Rule");

                    b.HasIndex(new[] { "SampleId", "IsResolved" }, "IX_AiDataQualityFlag_Sample");

                    b.ToTable("AiDataQualityFlag", null, t =>
                        {
                            t.HasComment("Kết quả chạy rule làm sạch trên từng mẫu");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiDataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Code")
                        .HasComment("breakdown-vi-v1, assignment-ranking-v1");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("CreatedBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("CreatedBy"), "utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("Languages")
                        .HasColumnType("json")
                        .HasColumnName("Languages")
                        .HasComment("[\"vi\",\"en\"]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TaskType")
                        .HasComment("Breakdown / Assignment");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_AiDataset_Name");

                    b.HasIndex(new[] { "Code" }, "UQ_AiDataset_Code")
                        .IsUnique();

                    b.ToTable("AiDataset", null, t =>
                        {
                            t.HasComment("Bộ dữ liệu huấn luyện");

                            t.HasCheckConstraint("CK_AiDataset_TaskType", "`TaskType` IN ('Breakdown','Assignment')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiDatasetSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("ContentHash")
                        .HasComment("SHA-256 của Instruction+Input+Output - khử trùng lặp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("DatasetVersionId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("DatasetVersionId"), "utf8mb4");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("InputJson")
                        .HasComment("Với Breakdown: {title, description, projectContext}. Với Assignment: {issue_features, candidates[]}");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("Instruction");

                    b.Property<bool>("IsPiiRedacted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsPiiRedacted")
                        .HasComment("BẮT BUỘC = 1 trước khi Approved. Story thật hay chứa tên KH, email, tên hệ thống nội bộ");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("vi")
                        .HasColumnName("Language");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("OutputJson")
                        .HasComment("Đầu ra CHUẨN đã qua người duyệt");

                    b.Property<decimal?>("QualityScore")
                        .HasColumnType("decimal(4,3)")
                        .HasColumnName("QualityScore")
                        .HasComment("0..1 do người duyệt chấm");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Raw")
                        .HasColumnName("QualityStatus")
                        .HasComment("Raw -> Cleaned -> Approved / Rejected");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("ReviewNote");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("NotReviewed")
                        .HasColumnName("ReviewStatus")
                        .HasComment("NotReviewed / Approved / Rejected / NeedsFix");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ReviewedAt");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("ReviewedBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ReviewedBy"), "utf8mb4");

                    b.Property<Guid?>("SourceRefId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SourceRefId")
                        .HasComment("XMOD: Id của bản ghi nguồn")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("SourceRefId"), "utf8mb4");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("SourceType")
                        .HasComment("AiSuggestedTask / AiAssignmentDecision / ManualCurated / Synthetic");

                    b.Property<string>("SplitType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Train")
                        .HasColumnName("SplitType")
                        .HasComment("Train / Validation / Test");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("int")
                        .HasColumnName("TokenCount")
                        .HasComment("Loại bỏ mẫu vượt context window");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NULL ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Instruction" }, "FT_AiDatasetSample_Instruction")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex(new[] { "ReviewStatus", "QualityStatus", "CreatedAt" }, "IX_AiDatasetSample_ReviewQueue");

                    b.HasIndex(new[] { "SourceType", "SourceRefId" }, "IX_AiDatasetSample_Source");

                    b.HasIndex(new[] { "DatasetVersionId", "SplitType", "QualityStatus" }, "IX_AiDatasetSample_Split");

                    b.HasIndex(new[] { "DatasetVersionId", "TokenCount" }, "IX_AiDatasetSample_TokenCount");

                    b.HasIndex(new[] { "DatasetVersionId", "ReviewStatus", "QualityStatus", "CreatedAt" }, "IX_AiDatasetSample_Version_Review");

                    b.HasIndex(new[] { "DatasetVersionId", "ContentHash" }, "UQ_AiDatasetSample_Dedup")
                        .IsUnique();

                    b.ToTable("AiDatasetSample", null, t =>
                        {
                            t.HasComment("Từng mẫu huấn luyện. Export ra JSONL từ bảng này");

                            t.HasCheckConstraint("CK_AiDatasetSample_Quality", "`QualityStatus` IN ('Raw','Cleaned','Approved','Rejected')");

                            t.HasCheckConstraint("CK_AiDatasetSample_Split", "`SplitType` IN ('Train','Validation','Test')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiDatasetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("Checksum")
                        .HasColumnType("char(64)")
                        .HasColumnName("Checksum")
                        .HasComment("SHA-256 của file JSONL export");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("DatasetId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("DatasetId"), "utf8mb4");

                    b.Property<string>("ExportPath")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ExportPath");

                    b.Property<DateTime?>("FrozenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FrozenAt");

                    b.Property<bool>("IsFrozen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsFrozen")
                        .HasComment("Đã đóng băng thì KHÔNG được sửa sample nữa");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<int>("SampleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SampleCount");

                    b.Property<int?>("SplitSeed")
                        .HasColumnType("int")
                        .HasColumnName("SplitSeed")
                        .HasComment("Seed chia split - BẮT BUỘC để tái lập được kết quả");

                    b.Property<int>("TestCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TestCount");

                    b.Property<int>("TrainCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TrainCount");

                    b.Property<int>("ValidationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ValidationCount");

                    b.Property<string>("VersionTag")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("VersionTag")
                        .HasComment("v1.0.0");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DatasetId", "VersionTag" }, "UQ_AiDatasetVersion")
                        .IsUnique();

                    b.ToTable("AiDatasetVersion", null, t =>
                        {
                            t.HasComment("Version hóa dataset - so sánh model chỉ có ý nghĩa khi cùng dataset version");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiEvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("DatasetVersionId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("DatasetVersionId"), "utf8mb4");

                    b.Property<DateTime>("EvaluatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EvaluatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("MetricName")
                        .HasComment("Breakdown: json_valid_rate, schema_match_rate, avg_edit_distance, keep_rate, rouge_l. Assignment: precision@1, ndcg@3, mae_workload_gap");

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("MetricValue");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ModelId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ModelId"), "utf8mb4");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Notes");

                    b.Property<int?>("SampleSize")
                        .HasColumnType("int")
                        .HasColumnName("SampleSize");

                    b.Property<string>("SplitType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Test")
                        .HasColumnName("SplitType");

                    b.Property<Guid?>("TrainingRunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TrainingRunId")
                        .HasComment("NULL nếu đánh giá model gốc / prompt thuần (baseline)")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("TrainingRunId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DatasetVersionId", "SplitType", "MetricName" }, "IX_AiEvaluationResult_Dataset_Metric");

                    b.HasIndex(new[] { "ModelId", "MetricName" }, "IX_AiEvaluationResult_Model");

                    b.HasIndex(new[] { "TrainingRunId", "MetricName" }, "IX_AiEvaluationResult_Run");

                    b.ToTable("AiEvaluationResult", null, t =>
                        {
                            t.HasComment("Không có bảng này thì không biết fine-tune có tốt hơn prompt thuần hay không");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiTrainingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("ArtifactPath")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ArtifactPath")
                        .HasComment("Đường dẫn adapter / .gguf sau khi convert");

                    b.Property<string>("BaseModelCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("BaseModelCode")
                        .HasComment("qwen2.5:3b-instruct");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("CreatedBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("CreatedBy"), "utf8mb4");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("DatasetVersionId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("DatasetVersionId"), "utf8mb4");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("DurationSeconds");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("ErrorMessage");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FinishedAt");

                    b.Property<string>("HardwareInfo")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("HardwareInfo")
                        .HasComment("GPU/CPU dùng để train, để so sánh công bằng");

                    b.Property<string>("Hyperparameters")
                        .HasColumnType("json")
                        .HasColumnName("Hyperparameters")
                        .HasComment("lora_r, lora_alpha, lr, epochs, batch_size, seed");

                    b.Property<string>("LogPath")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("LogPath");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("LoRA")
                        .HasColumnName("Method")
                        .HasComment("LoRA / QLoRA / FullFineTune / GBDT (cho assignment)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Queued")
                        .HasColumnName("Status")
                        .HasComment("Queued / Running / Completed / Failed / Cancelled");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TaskType");

                    b.Property<decimal?>("TrainLoss")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("TrainLoss");

                    b.Property<decimal?>("ValidationLoss")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("ValidationLoss");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DatasetVersionId" }, "IX_AiTrainingRun_Dataset");

                    b.HasIndex(new[] { "Name" }, "IX_AiTrainingRun_Name");

                    b.HasIndex(new[] { "Status", "CreatedAt" }, "IX_AiTrainingRun_Status_Created");

                    b.HasIndex(new[] { "TaskType", "Status", "CreatedAt" }, "IX_AiTrainingRun_Task_Status");

                    b.ToTable("AiTrainingRun", null, t =>
                        {
                            t.HasComment("Mỗi lần fine-tune - lưu đủ để tái lập thí nghiệm");

                            t.HasCheckConstraint("CK_AiTrainingRun_Status", "`Status` IN ('Queued','Running','Completed','Failed','Cancelled')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("ContentType")
                        .HasComment("BỔ SUNG: cần cho Content-Disposition khi tải về");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FileName")
                        .HasComment("Tên file gốc");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("FileSizeBytes")
                        .HasComment("BỔ SUNG: kiểm tra quota");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("StoredPath")
                        .HasComment("Đường dẫn local / S3 key");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("UploadedBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UploadedBy"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_Attachment_CreatedAt");

                    b.HasIndex(new[] { "FileName" }, "IX_Attachment_FileName");

                    b.HasIndex(new[] { "IssueId" }, "IX_Attachment_Issue");

                    b.ToTable("Attachment", null, t =>
                        {
                            t.HasComment("File đính kèm");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("Content")
                        .HasComment("Markdown");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsEdited");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<string>("MentionedUserIds")
                        .HasColumnType("json")
                        .HasColumnName("MentionedUserIds")
                        .HasComment("BỔ SUNG: mảng GUID được @mention, để module Notification xử lý");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ParentCommentId")
                        .HasComment("BỔ SUNG: reply lồng nhau")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ParentCommentId"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NULL ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Content" }, "FT_Comment_Content")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex(new[] { "IssueId", "CreatedAt" }, "IX_Comment_Issue");

                    b.HasIndex(new[] { "ParentCommentId" }, "IX_Comment_Parent");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "IX_Comment_User_Created");

                    b.ToTable("Comment", null, t =>
                        {
                            t.HasComment("Bình luận do người dùng chủ động viết");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<Guid?>("AiGenerationLogId")
                        .HasColumnType("char(36)")
                        .HasColumnName("AiGenerationLogId")
                        .HasComment("XMOD -> AiGenerationLog.Id. Truy vết sub-task đến từ request AI nào")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("AiGenerationLogId"), "utf8mb4");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("AssigneeId")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("AssigneeId"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasColumnType("mediumtext")
                        .HasColumnName("Description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("DueDate");

                    b.Property<Guid?>("EpicId")
                        .HasColumnType("char(36)")
                        .HasColumnName("EpicId")
                        .HasComment("BỔ SUNG: denormalize Epic gốc, tránh đệ quy khi gom nhóm Backlog")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("EpicId"), "utf8mb4");

                    b.Property<bool>("IsAiAssigned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsAiAssigned")
                        .HasComment("BỔ SUNG: assignee hiện tại do AI gợi ý và được chấp nhận");

                    b.Property<bool>("IsAiGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsAiGenerated")
                        .HasComment("Sub-task do AI Breakdown sinh ra");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("int")
                        .HasColumnName("IssueNumber")
                        .HasComment("BỔ SUNG: số thứ tự trong project, ghép Project.ProjectKey thành \"PROJ-123\"");

                    b.Property<Guid>("IssueTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueTypeId")
                        .HasComment("XMOD -> IssueType.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueTypeId"), "utf8mb4");

                    b.Property<int?>("OriginalEstimateMinutes")
                        .HasColumnType("int")
                        .HasColumnName("OriginalEstimateMinutes");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ParentId")
                        .HasComment("Self-ref: Epic -> Story -> Sub-task")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ParentId"), "utf8mb4");

                    b.Property<Guid?>("PriorityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("PriorityId")
                        .HasComment("XMOD -> Priority.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("PriorityId"), "utf8mb4");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .HasComment("XMOD -> Project.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.Property<decimal>("RankOrder")
                        .HasColumnType("decimal(30,15)")
                        .HasColumnName("RankOrder")
                        .HasComment("Chèn giữa = trung bình cộng 2 rank kề. Job rebalance khi khoảng cách < 1e-9");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ReporterId")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ReporterId"), "utf8mb4");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ResolvedAt")
                        .HasComment("AI ASSIGNMENT: thời điểm vào Done, dùng tính cycle time");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SprintId")
                        .HasComment("XMOD -> Sprint.Id. NULL = còn ở Backlog")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("SprintId"), "utf8mb4");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartedAt")
                        .HasComment("AI ASSIGNMENT: lần đầu vào trạng thái InProgress");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("StatusId")
                        .HasComment("XMOD -> WorkflowStatus.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("StatusId"), "utf8mb4");

                    b.Property<decimal?>("StoryPoints")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("StoryPoints")
                        .HasComment("DECIMAL thay INT để hỗ trợ 0.5 point");

                    b.Property<int>("TimeSpentMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TimeSpentMinutes")
                        .HasComment("AI ASSIGNMENT: feature ước lượng độ chính xác");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NULL ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Title", "Description" }, "FT_Issue_Search")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex(new[] { "AiGenerationLogId" }, "IX_Issue_AiLog");

                    b.HasIndex(new[] { "AssigneeId", "StatusId" }, "IX_Issue_Assignee");

                    b.HasIndex(new[] { "AssigneeId", "IsDeleted", "StatusId", "DueDate" }, "IX_Issue_Assignee_Workload");

                    b.HasIndex(new[] { "ProjectId", "SprintId", "RankOrder" }, "IX_Issue_Backlog");

                    b.HasIndex(new[] { "SprintId", "StatusId", "IsDeleted", "RankOrder" }, "IX_Issue_Board_Filter");

                    b.HasIndex(new[] { "EpicId" }, "IX_Issue_Epic");

                    b.HasIndex(new[] { "ParentId" }, "IX_Issue_Parent");

                    b.HasIndex(new[] { "ProjectId", "IsDeleted", "DueDate" }, "IX_Issue_Project_Due");

                    b.HasIndex(new[] { "ProjectId", "IsDeleted", "CreatedAt" }, "IX_Issue_Project_Recent");

                    b.HasIndex(new[] { "ReporterId", "CreatedAt" }, "IX_Issue_Reporter_Created");

                    b.HasIndex(new[] { "ProjectId", "ResolvedAt" }, "IX_Issue_Resolved");

                    b.HasIndex(new[] { "SprintId", "StatusId" }, "IX_Issue_Sprint_Status");

                    b.HasIndex(new[] { "ProjectId", "IssueNumber" }, "UQ_Issue_Key")
                        .IsUnique();

                    b.ToTable("Issue", null, t =>
                        {
                            t.HasComment("Entity trung tâm: Epic/Story/Task/Bug/Sub-task");

                            t.HasCheckConstraint("CK_Issue_AiLogConsistency", "`IsAiGenerated` = 0 OR `AiGenerationLogId` IS NOT NULL");

                            t.HasCheckConstraint("CK_Issue_Points", "`StoryPoints` IS NULL OR `StoryPoints` >= 0");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueAssignmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<Guid?>("AiCandidateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("AiCandidateId")
                        .HasComment("XMOD -> AiAssignmentCandidate.Id nếu đến từ gợi ý AI")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("AiCandidateId"), "utf8mb4");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AssignedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("AssignedBy")
                        .HasComment("XMOD -> User.Id. NULL nếu do AI tự gán")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("AssignedBy"), "utf8mb4");

                    b.Property<string>("AssignmentSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("AssignmentSource")
                        .HasComment("Manual / AiSuggested / AiAuto / SelfPick");

                    b.Property<Guid?>("FromAssigneeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("FromAssigneeId")
                        .HasComment("XMOD -> User.Id. NULL = chưa gán ai")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("FromAssigneeId"), "utf8mb4");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<string>("Reason")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Reason")
                        .HasComment("Lý do override nếu PM không theo gợi ý AI");

                    b.Property<decimal?>("StoryPointsAtTime")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("StoryPointsAtTime")
                        .HasComment("Snapshot point tại thời điểm gán (point có thể bị đổi sau)");

                    b.Property<Guid?>("ToAssigneeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ToAssigneeId")
                        .HasComment("XMOD -> User.Id. NULL = gỡ assignee")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ToAssigneeId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AssignedAt" }, "IX_IssueAssignHistory_AssignedAt");

                    b.HasIndex(new[] { "IssueId", "AssignedAt" }, "IX_IssueAssignHistory_Issue");

                    b.HasIndex(new[] { "AssignmentSource", "AssignedAt" }, "IX_IssueAssignHistory_Source");

                    b.HasIndex(new[] { "ToAssigneeId", "AssignedAt" }, "IX_IssueAssignHistory_To");

                    b.ToTable("IssueAssignmentHistory", null, t =>
                        {
                            t.HasComment("BỔ SUNG - BẢNG QUAN TRỌNG NHẤT cho AI phân phối task: toàn bộ lịch sử giao việc + nguồn gán");

                            t.HasCheckConstraint("CK_IssueAssignHistory_Source", "`AssignmentSource` IN ('Manual','AiSuggested','AiAuto','SelfPick')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueComponentLink", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ComponentId")
                        .HasComment("XMOD -> ProjectComponent.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ComponentId"), "utf8mb4");

                    b.HasKey("IssueId", "ComponentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ComponentId" }, "IX_IssueComponent_Component");

                    b.ToTable("IssueComponentLink", null, t =>
                        {
                            t.HasComment("BỔ SUNG: v2.0 yêu cầu báo cáo theo Component nhưng thiếu bảng nối này");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueLabel", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("char(36)")
                        .HasColumnName("LabelId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("LabelId"), "utf8mb4");

                    b.HasKey("IssueId", "LabelId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LabelId" }, "IX_IssueLabel_Label");

                    b.ToTable("IssueLabel", null, t =>
                        {
                            t.HasComment("N-N Issue <-> Label");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("CreatedBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("CreatedBy"), "utf8mb4");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LinkType")
                        .HasComment("Blocks / IsBlockedBy / Relates / Duplicates / IsDuplicatedBy");

                    b.Property<Guid>("SourceIssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SourceIssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("SourceIssueId"), "utf8mb4");

                    b.Property<Guid>("TargetIssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TargetIssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TargetIssueId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TargetIssueId" }, "IX_IssueLink_Target");

                    b.HasIndex(new[] { "SourceIssueId", "TargetIssueId", "LinkType" }, "UQ_IssueLink")
                        .IsUnique();

                    b.ToTable("IssueLink", null, t =>
                        {
                            t.HasComment("Quan hệ ngang giữa issue. Tạo Blocks thì tự sinh bản ghi IsBlockedBy ngược chiều");

                            t.HasCheckConstraint("CK_IssueLink_NotSelf", "`SourceIssueId` <> `TargetIssueId`");

                            t.HasCheckConstraint("CK_IssueLink_Type", "`LinkType` IN ('Blocks','IsBlockedBy','Relates','Duplicates','IsDuplicatedBy')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueRequiredSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<sbyte>("MinLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("MinLevel")
                        .HasComment("1..5");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SkillId")
                        .HasComment("XMOD -> SkillCatalog.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("SkillId"), "utf8mb4");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("Source")
                        .HasComment("Manual / AI / DerivedFromComponent");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,3)")
                        .HasDefaultValue(1.000m)
                        .HasColumnName("Weight")
                        .HasComment("Trọng số khi tính skill-match score");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SkillId" }, "IX_IssueRequiredSkill_Skill");

                    b.HasIndex(new[] { "IssueId", "SkillId" }, "UQ_IssueRequiredSkill")
                        .IsUnique();

                    b.ToTable("IssueRequiredSkill", null, t =>
                        {
                            t.HasComment("BỔ SUNG - AI ASSIGNMENT: kỹ năng yêu cầu của task, ghép với UserSkill để tính skill-match");

                            t.HasCheckConstraint("CK_IssueRequiredSkill_Level", "`MinLevel` BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_IssueRequiredSkill_Source", "`Source` IN ('Manual','AI','DerivedFromComponent')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ChangedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("ChangedBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ChangedBy"), "utf8mb4");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("DurationSeconds")
                        .HasComment("Thời gian ĐÃ Ở trạng thái trước đó - tính sẵn khi ghi");

                    b.Property<string>("FromCategory")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FromCategory");

                    b.Property<Guid?>("FromStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("FromStatusId")
                        .HasComment("XMOD. NULL = trạng thái đầu tiên khi tạo")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("FromStatusId"), "utf8mb4");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<string>("ToCategory")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ToCategory");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ToStatusId")
                        .HasComment("XMOD -> WorkflowStatus.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ToStatusId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ToCategory", "ChangedAt" }, "IX_IssueStatusHistory_Category_Date");

                    b.HasIndex(new[] { "ChangedAt" }, "IX_IssueStatusHistory_ChangedAt");

                    b.HasIndex(new[] { "IssueId", "ChangedAt" }, "IX_IssueStatusHistory_Issue");

                    b.ToTable("IssueStatusHistory", null, t =>
                        {
                            t.HasComment("BỔ SUNG - AI ASSIGNMENT: ActivityLog dạng text không tính được cycle time. Bảng này lưu có cấu trúc + duration tính sẵn");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueVersionLink", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("VersionId")
                        .HasComment("XMOD -> ProjectVersion.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("VersionId"), "utf8mb4");

                    b.Property<string>("LinkType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("FixVersion")
                        .HasColumnName("LinkType")
                        .HasComment("FixVersion / AffectsVersion");

                    b.HasKey("IssueId", "VersionId", "LinkType")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "VersionId" }, "IX_IssueVersion_Version");

                    b.ToTable("IssueVersionLink", null, t =>
                        {
                            t.HasComment("BỔ SUNG: bảng nối Issue <-> Version cho release note");

                            t.HasCheckConstraint("CK_IssueVersion_LinkType", "`LinkType` IN ('FixVersion','AffectsVersion')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueWatcher", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.HasKey("IssueId", "UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "IX_IssueWatcher_UserId");

                    b.ToTable("IssueWatcher", null, t =>
                        {
                            t.HasComment("N-N theo dõi issue");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(7)")
                        .HasDefaultValue("#DFE1E6")
                        .HasColumnName("ColorHex");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .HasComment("XMOD -> Project.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "IX_Label_Name");

                    b.HasIndex(new[] { "ProjectId", "Name" }, "UQ_Label_Name")
                        .IsUnique();

                    b.ToTable("Label", null, t =>
                        {
                            t.HasComment("Nhãn tự do theo project");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.SprintVelocity", b =>
                {
                    b.Property<decimal>("CommittedPoints")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CompletedPoints")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<long>("IssueCount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SprintName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.ToTable((string)null);

                    b.ToView("vw_SprintVelocity", (string)null);
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.UserActiveWorkload", b =>
                {
                    b.Property<decimal>("InProgressCount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("InProgressPoints")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("OpenIssueCount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OpenPoints")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OverdueCount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("vw_UserActiveWorkload", (string)null);
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AcceptanceCriteria", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AcceptanceCriteria_Issue");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ActivityLog_Issue");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiDataQualityFlag", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.AiDataCleaningRule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AiDataQualityFlag_Rule");

                    b.HasOne("DeliveryIntelligence.Domain.Entities.AiDatasetSample", null)
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AiDataQualityFlag_Sample");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiDatasetSample", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.AiDatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AiDatasetSample_Version");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiDatasetVersion", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.AiDataset", null)
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AiDatasetVersion_Dataset");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiEvaluationResult", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.AiDatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AiEvaluationResult_Dataset");

                    b.HasOne("DeliveryIntelligence.Domain.Entities.AiTrainingRun", null)
                        .WithMany()
                        .HasForeignKey("TrainingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_AiEvaluationResult_TrainingRun");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.AiTrainingRun", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.AiDatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AiTrainingRun_Dataset");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Attachment_Issue");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.Comment", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Comment_Issue");

                    b.HasOne("DeliveryIntelligence.Domain.Entities.Comment", null)
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Comment_Parent");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.Issue", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Issue_Parent");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueAssignmentHistory", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueAssignHistory_Issue");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueComponentLink", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueComponent_Issue");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueLabel", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueLabel_Issue");

                    b.HasOne("DeliveryIntelligence.Domain.Entities.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueLabel_Label");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueLink", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("SourceIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueLink_Source");

                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("TargetIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueLink_Target");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueRequiredSkill", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueRequiredSkill_Issue");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueStatusHistory", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueStatusHistory_Issue");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueVersionLink", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueVersion_Issue");
                });

            modelBuilder.Entity("DeliveryIntelligence.Domain.Entities.IssueWatcher", b =>
                {
                    b.HasOne("DeliveryIntelligence.Domain.Entities.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueWatcher_Issue");
                });
#pragma warning restore 612, 618
        }
    }
}
