<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProjectMgmt.Contracts\ProjectMgmt.Contracts.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Core\ProjectMgmt.Core.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Modules.DeliveryIntelligence\Application\DeliveryIntelligence.Application.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Modules.DeliveryIntelligence\Infrastructure\DeliveryIntelligence.Infrastructure.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Modules.IdentityExperience\Application\IdentityExperience.Application.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Modules.IdentityExperience\Infrastructure\IdentityExperience.Infrastructure.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Modules.Planning\Application\Planning.Application.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Modules.Planning\Infrastructure\Planning.Infrastructure.csproj" />
    <ProjectReference Include="..\ProjectMgmt.Solution\ProjectMgmt.Solution.csproj" />
  </ItemGroup>
</Project>
