// <auto-generated />
using System;
using IdentityExperience.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityExperience.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityExperienceDbContext))]
    partial class IdentityExperienceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IdentityExperience.Domain.Entities.AiGenerationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AppliedAt")
                        .HasComment("Thời điểm user bấm \"Áp dụng\". NULL = chưa từng áp dụng");

                    b.Property<int>("AppliedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("AppliedCount")
                        .HasComment("Số sub-task thực sự được tạo (có thể < số gợi ý)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CompletedAt");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("int")
                        .HasColumnName("CompletionTokens");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ErrorCode")
                        .HasComment("Timeout / InvalidJson / SchemaMismatch / OllamaUnavailable");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("ErrorMessage");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("HangfireJobId")
                        .HasComment("Truy vết ngược sang Hangfire dashboard khi debug");

                    b.Property<string>("InputText")
                        .HasColumnType("text")
                        .HasColumnName("InputText")
                        .HasComment("Mô tả bổ sung người dùng nhập");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("IssueId")
                        .HasComment("XMOD -> Issue.Id (Story gốc được yêu cầu chia nhỏ)")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IssueId"), "utf8mb4");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int")
                        .HasColumnName("LatencyMs")
                        .HasComment("Theo dõi hiệu năng model cục bộ");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ModelId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ModelId"), "utf8mb4");

                    b.Property<string>("ParsedJson")
                        .HasColumnType("json")
                        .HasColumnName("ParsedJson")
                        .HasComment("Sau khi parse & validate schema");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .HasComment("XMOD -> Project.Id. Denormalize để rate-limit theo project không phải JOIN")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ProjectId"), "utf8mb4");

                    b.Property<Guid?>("PromptTemplateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("PromptTemplateId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("PromptTemplateId"), "utf8mb4");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("int")
                        .HasColumnName("PromptTokens");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("mediumtext")
                        .HasColumnName("RawResponseJson")
                        .HasComment("Phản hồi thô trước khi parse, phục vụ audit & đổi logic parse");

                    b.Property<string>("RenderedPrompt")
                        .HasColumnType("mediumtext")
                        .HasColumnName("RenderedPrompt")
                        .HasComment("Prompt cuối cùng đã ghép - BẮT BUỘC lưu để tái lập kết quả");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("RetryCount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Status")
                        .HasComment("Pending / Processing / Completed / Failed / Cancelled");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .HasComment("XMOD -> User.Id (PO/Tech Lead kích hoạt)")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ErrorCode", "CreatedAt" }, "IX_AiGenerationLog_Error");

                    b.HasIndex(new[] { "HangfireJobId" }, "IX_AiGenerationLog_HangfireJobId");

                    b.HasIndex(new[] { "IssueId", "CreatedAt" }, "IX_AiGenerationLog_Issue");

                    b.HasIndex(new[] { "ProjectId", "CreatedAt" }, "IX_AiGenerationLog_RateLimit");

                    b.HasIndex(new[] { "Status", "CreatedAt" }, "IX_AiGenerationLog_Status");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "IX_AiGenerationLog_User");

                    b.ToTable("AiGenerationLog", null, t =>
                        {
                            t.HasComment("Mỗi lần yêu cầu AI chia nhỏ Story");

                            t.HasCheckConstraint("CK_AiGenerationLog_Status", "`Status` IN ('Pending','Processing','Completed','Failed','Cancelled')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.AiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("AdapterPath")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AdapterPath")
                        .HasComment("Đường dẫn LoRA adapter / Modelfile");

                    b.Property<string>("BaseModelCode")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("BaseModelCode")
                        .HasComment("Model gốc nếu đây là bản fine-tune");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Code")
                        .HasComment("qwen2.5:3b-instruct, qwen2.5:3b-scrum-lora-v1");

                    b.Property<int?>("ContextWindow")
                        .HasColumnType("int")
                        .HasColumnName("ContextWindow");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DefaultParams")
                        .HasColumnType("json")
                        .HasColumnName("DefaultParams")
                        .HasComment("temperature, top_p, num_predict, seed...");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DisplayName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsActive")
                        .HasComment("Model đang được dùng ở production");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Ollama")
                        .HasColumnName("Provider")
                        .HasComment("Ollama / OpenAI / Local");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TaskType")
                        .HasComment("Breakdown / Assignment / Embedding");

                    b.Property<Guid?>("TrainingRunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TrainingRunId")
                        .HasComment("XMOD -> AiTrainingRun.Id nếu sinh từ fine-tune")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("TrainingRunId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DisplayName" }, "IX_AiModel_DisplayName");

                    b.HasIndex(new[] { "TaskType", "IsActive" }, "IX_AiModel_Task_Active");

                    b.HasIndex(new[] { "Code" }, "UQ_AiModel_Code")
                        .IsUnique();

                    b.ToTable("AiModel", null, t =>
                        {
                            t.HasComment("Registry model - BẮT BUỘC có nếu định fine-tune: phải biết kết quả nào sinh bởi model nào để so sánh A/B");

                            t.HasCheckConstraint("CK_AiModel_TaskType", "`TaskType` IN ('Breakdown','Assignment','Embedding')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.AiPromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Code")
                        .HasComment("breakdown.system.v1");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("CreatedBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("CreatedBy"), "utf8mb4");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsActive");

                    b.Property<string>("JsonSchema")
                        .HasColumnType("json")
                        .HasColumnName("JsonSchema")
                        .HasComment("QUAN TRỌNG: schema gửi vào tham số `format` của Ollama để ÉP định dạng ở mức decoder. Giải quyết bài toán \"AI sinh task thừa/sai format\" mà KHÔNG cần fine-tune");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("vi")
                        .HasColumnName("Language")
                        .HasComment("vi / en / auto");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("SystemPrompt");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TaskType");

                    b.Property<string>("UserTemplate")
                        .HasColumnType("mediumtext")
                        .HasColumnName("UserTemplate")
                        .HasComment("Template có placeholder {{Title}}, {{Description}}, {{IssueTypes}}");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Version");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TaskType", "IsActive" }, "IX_AiPromptTemplate_Active");

                    b.HasIndex(new[] { "Code", "Version" }, "UQ_AiPromptTemplate")
                        .IsUnique();

                    b.ToTable("AiPromptTemplate", null, t =>
                        {
                            t.HasComment("Prompt có version - không hard-code prompt trong C#, nếu không sẽ không A/B test được");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.AiSuggestedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<Guid>("AiGenerationLogId")
                        .HasColumnType("char(36)")
                        .HasColumnName("AiGenerationLogId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("AiGenerationLogId"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("CreatedIssueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CreatedIssueId")
                        .HasComment("XMOD -> Issue.Id nếu đã được tạo thành Sub-task thật")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("CreatedIssueId"), "utf8mb4");

                    b.Property<decimal?>("EditDistanceRatio")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("EditDistanceRatio")
                        .HasComment("0.0 = giữ nguyên, 1.0 = viết lại hoàn toàn. Tính bằng Levenshtein chuẩn hóa");

                    b.Property<string>("FinalAcceptanceCriteria")
                        .HasColumnType("json")
                        .HasColumnName("FinalAcceptanceCriteria");

                    b.Property<string>("FinalDescription")
                        .HasColumnType("text")
                        .HasColumnName("FinalDescription");

                    b.Property<decimal?>("FinalEstimatePoints")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("FinalEstimatePoints");

                    b.Property<string>("FinalSummary")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("FinalSummary");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("OrderIndex");

                    b.Property<string>("OriginalAcceptanceCriteria")
                        .HasColumnType("json")
                        .HasColumnName("OriginalAcceptanceCriteria")
                        .HasComment("Mảng chuỗi AC do AI sinh");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("text")
                        .HasColumnName("OriginalDescription");

                    b.Property<decimal?>("OriginalEstimatePoints")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("OriginalEstimatePoints");

                    b.Property<string>("OriginalSuggestedSkills")
                        .HasColumnType("json")
                        .HasColumnName("OriginalSuggestedSkills")
                        .HasComment("AI gợi ý skill cần có -> nạp vào IssueRequiredSkill");

                    b.Property<string>("OriginalSummary")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("OriginalSummary");

                    b.Property<string>("RejectReason")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("RejectReason")
                        .HasComment("Vì sao bỏ gợi ý này - dữ liệu vàng để cải thiện prompt");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ReviewedAt");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("ReviewedBy")
                        .HasComment("XMOD -> User.Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ReviewedBy"), "utf8mb4");

                    b.Property<string>("UserAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("UserAction")
                        .HasComment("Pending / Kept / Edited / Rejected — ĐÂY LÀ NHÃN HUẤN LUYỆN QUAN TRỌNG NHẤT");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OriginalSummary", "OriginalDescription", "FinalSummary", "FinalDescription" }, "FT_AiSuggestedTask_Search")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex(new[] { "UserAction", "CreatedAt" }, "IX_AiSuggestedTask_Action");

                    b.HasIndex(new[] { "CreatedIssueId" }, "IX_AiSuggestedTask_CreatedIssue");

                    b.HasIndex(new[] { "AiGenerationLogId", "OrderIndex" }, "IX_AiSuggestedTask_Log");

                    b.ToTable("AiSuggestedTask", null, t =>
                        {
                            t.HasComment("BẢNG CỐT LÕI CHO FINE-TUNE. Chỉ lưu RawResponseJson như thiết kế v2.0 thì KHÔNG BAO GIỜ biết người dùng đã sửa gì -> mất sạch tín hiệu huấn luyện");

                            t.HasCheckConstraint("CK_AiSuggestedTask_Action", "`UserAction` IN ('Pending','Kept','Edited','Rejected')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LinkedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Provider")
                        .HasComment("Google / Microsoft / Facebook");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ProviderKey")
                        .HasComment("claim \"sub\" - KHÔNG dùng email vì email đổi được");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "IX_ExternalLogin_UserId");

                    b.HasIndex(new[] { "Provider", "ProviderKey" }, "UQ_ExternalLogin_Provider")
                        .IsUnique();

                    b.ToTable("ExternalLogin", null, t =>
                        {
                            t.HasComment("Liên kết đăng nhập OAuth2");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ActorId")
                        .HasComment("XMOD -> User.Id. NULL = do hệ thống/AI")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ActorId"), "utf8mb4");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("EntityId")
                        .HasComment("BỔ SUNG: v2.0 thiếu cột này -> bấm vào thông báo không biết đi đâu")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("EntityId"), "utf8mb4");

                    b.Property<string>("EntityType")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EntityType")
                        .HasComment("BỔ SUNG: Issue / Sprint / Project / AiGenerationLog");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRead");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProjectId")
                        .HasComment("XMOD: lọc thông báo theo project")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ProjectId"), "utf8mb4");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ReadAt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Type")
                        .HasComment("IssueAssigned / NewComment / Mention / SprintEnding / AiBreakdownCompleted / AiBreakdownFailed / AiAssignmentReady");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .HasComment("XMOD -> User.Id (người nhận)")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Title", "Content" }, "FT_Notification_Search")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex(new[] { "EntityType", "EntityId" }, "IX_Notification_Entity");

                    b.HasIndex(new[] { "UserId", "IsRead", "CreatedAt" }, "IX_Notification_Inbox");

                    b.HasIndex(new[] { "ProjectId", "CreatedAt" }, "IX_Notification_Project_Created");

                    b.HasIndex(new[] { "Type", "CreatedAt" }, "IX_Notification_Type_Created");

                    b.ToTable("Notification", null, t =>
                        {
                            t.HasComment("Thông báo, kết hợp SignalR đẩy realtime");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("AttemptCount")
                        .HasComment("Chống brute-force, khóa sau N lần");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CodeHash")
                        .HasComment("HASH của OTP, không lưu plain-text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ExpiresAt");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsUsed")
                        .HasComment("Chống replay");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Purpose")
                        .HasComment("VerifyEmail / ResetPassword / Login2FA");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ExpiresAt" }, "IX_OtpCode_ExpiresAt");

                    b.HasIndex(new[] { "UserId", "Purpose", "IsUsed" }, "IX_OtpCode_User_Purpose");

                    b.ToTable("OtpCode", null, t =>
                        {
                            t.HasComment("Mã OTP đa mục đích");

                            t.HasCheckConstraint("CK_OtpCode_Purpose", "`Purpose` IN ('VerifyEmail','ResetPassword','Login2FA')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Code")
                        .HasComment("issue.create, sprint.close, ai.breakdown.request...");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("Grouping")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Grouping")
                        .HasComment("Nhóm hiển thị trên UI phân quyền");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "UQ_Permission_Code")
                        .IsUnique();

                    b.ToTable("Permission", null, t =>
                        {
                            t.HasComment("Danh mục hành động nhỏ nhất có thể cấp phép");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("varchar(45)")
                        .HasColumnName("CreatedByIp")
                        .HasComment("IPv6-safe");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ExpiresAt");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRevoked");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ReplacedByTokenId")
                        .HasComment("Chuỗi rotation - phát hiện token reuse attack")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ReplacedByTokenId"), "utf8mb4");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("TokenHash")
                        .HasComment("SHA-256 hex của refresh token");

                    b.Property<string>("UserAgent")
                        .HasColumnType("varchar(400)")
                        .HasColumnName("UserAgent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ExpiresAt" }, "IX_RefreshToken_ExpiresAt");

                    b.HasIndex(new[] { "UserId", "IsRevoked" }, "IX_RefreshToken_UserId");

                    b.HasIndex(new[] { "TokenHash" }, "UQ_RefreshToken_Hash")
                        .IsUnique();

                    b.ToTable("RefreshToken", null, t =>
                        {
                            t.HasComment("Chỉ RefreshToken lưu DB; Access Token JWT tự-chứa nên không lưu");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsSystem")
                        .HasComment("Vai trò hệ thống, không cho xóa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Scope")
                        .HasComment("Phạm vi mặc định: System / Organization / Project");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "UQ_Role_Name")
                        .IsUnique();

                    b.ToTable("Role", null, t =>
                        {
                            t.HasComment("Danh mục vai trò RBAC");

                            t.HasCheckConstraint("CK_Role_Scope", "`Scope` IN ('System','Organization','Project')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("RoleId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("RoleId"), "utf8mb4");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("PermissionId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("PermissionId"), "utf8mb4");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PermissionId" }, "IX_RolePermission_PermissionId");

                    b.ToTable("RolePermission", null, t =>
                        {
                            t.HasComment("N-N Role <-> Permission");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.SkillCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("Category")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Category")
                        .HasComment("Backend / Frontend / Database / QA / DevOps / Design");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Code")
                        .HasComment("dotnet, angular, sql, devops, testing...");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Category", "Name" }, "IX_SkillCatalog_Category_Name");

                    b.HasIndex(new[] { "Name" }, "IX_SkillCatalog_Name");

                    b.HasIndex(new[] { "Code" }, "UQ_SkillCatalog_Code")
                        .IsUnique();

                    b.ToTable("SkillCatalog", null, t =>
                        {
                            t.HasComment("Danh mục kỹ năng chuẩn hóa, dùng chung cho user và issue");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasComment("GUID - PK toàn hệ thống")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Email")
                        .HasComment("Định danh đăng nhập chính");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive")
                        .HasComment("Soft-disable, không xóa dữ liệu");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsEmailVerified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastLoginAt");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("NormalizedEmail")
                        .HasComment("Email viết HOA để so sánh không phân biệt hoa/thường");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PasswordHash")
                        .HasComment("BCrypt/Argon2. NULL nếu tài khoản thuần OAuth");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("char(36)")
                        .HasColumnName("SecurityStamp")
                        .HasComment("Đổi giá trị này để vô hiệu toàn bộ token cũ")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("SecurityStamp"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NULL ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IsActive", "CreatedAt" }, "IX_User_Active_Created");

                    b.HasIndex(new[] { "LastLoginAt" }, "IX_User_LastLoginAt");

                    b.HasIndex(new[] { "NormalizedEmail" }, "UQ_User_NormalizedEmail")
                        .IsUnique();

                    b.ToTable("User", null, t =>
                        {
                            t.HasComment("Tài khoản đăng nhập cốt lõi");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AvatarUrl");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("Bio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("JobTitle")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("JobTitle")
                        .HasComment("AI ASSIGNMENT: dùng cho cold-start người mới");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("SeniorityLevel")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SeniorityLevel")
                        .HasComment("Intern/Junior/Middle/Senior/Lead - cold-start");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("Asia/Ho_Chi_Minh")
                        .HasColumnName("Timezone");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NULL ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.Property<decimal?>("YearsOfExperience")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("YearsOfExperience")
                        .HasComment("Cold-start khi chưa có log task");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DisplayName", "JobTitle", "Bio" }, "FT_UserProfile_Search")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.HasIndex(new[] { "DisplayName" }, "IX_UserProfile_DisplayName");

                    b.HasIndex(new[] { "JobTitle" }, "IX_UserProfile_JobTitle");

                    b.HasIndex(new[] { "UserId" }, "UQ_UserProfile_UserId")
                        .IsUnique();

                    b.ToTable("UserProfile", null, t =>
                        {
                            t.HasComment("Thông tin cá nhân, tách khỏi bảng bảo mật User (1-1)");

                            t.HasCheckConstraint("CK_UserProfile_Seniority", "`SeniorityLevel` IS NULL OR `SeniorityLevel` IN ('Intern','Junior','Middle','Senior','Lead','Principal')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("GrantedBy")
                        .HasComment("Ai là người gán vai trò này")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("GrantedBy"), "utf8mb4");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("RoleId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("RoleId"), "utf8mb4");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ScopeId")
                        .HasComment("XMOD: Id của Organization hoặc Project. NULL nếu ScopeType=System")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ScopeId"), "utf8mb4");

                    b.Property<Guid?>("ScopeKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("char(36)")
                        .HasColumnName("ScopeKey")
                        .HasComputedColumnSql("IFNULL(`ScopeId`, '00000000-0000-0000-0000-000000000000')", true)
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ScopeKey"), "utf8mb4");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ScopeType")
                        .HasComment("System / Organization / Project");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId", "ScopeType", "ScopeId" }, "IX_UserRole_Lookup");

                    b.HasIndex(new[] { "ScopeType", "ScopeId" }, "IX_UserRole_Scope");

                    b.HasIndex(new[] { "UserId", "RoleId", "ScopeType", "ScopeKey" }, "UQ_UserRole_Scoped")
                        .IsUnique();

                    b.ToTable("UserRole", null, t =>
                        {
                            t.HasComment("Gán vai trò có phạm vi, thay cho OrgMember/ProjectMember riêng");

                            t.HasCheckConstraint("CK_UserRole_ScopeType", "`ScopeType` IN ('System','Organization','Project')");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.UserSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "utf8mb4");

                    b.Property<bool>("IsSelfDeclared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IsSelfDeclared")
                        .HasComment("0 = đã được lead xác nhận, tin cậy hơn");

                    b.Property<sbyte>("ProficiencyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)3)
                        .HasColumnName("ProficiencyLevel")
                        .HasComment("1..5 - do user tự khai hoặc lead đánh giá");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SkillId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("SkillId"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("NULL ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("UserId"), "utf8mb4");

                    b.Property<decimal?>("YearsOfExperience")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("YearsOfExperience");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SkillId", "ProficiencyLevel" }, "IX_UserSkill_SkillId");

                    b.HasIndex(new[] { "UserId", "SkillId" }, "UQ_UserSkill")
                        .IsUnique();

                    b.ToTable("UserSkill", null, t =>
                        {
                            t.HasComment("AI ASSIGNMENT: nguồn dữ liệu chính cho cold-start người mới vào project");

                            t.HasCheckConstraint("CK_UserSkill_Level", "`ProficiencyLevel` BETWEEN 1 AND 5");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.AiGenerationLog", b =>
                {
                    b.HasOne("IdentityExperience.Domain.Entities.AiModel", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AiGenerationLog_Model");

                    b.HasOne("IdentityExperience.Domain.Entities.AiPromptTemplate", null)
                        .WithMany()
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AiGenerationLog_Prompt");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.AiSuggestedTask", b =>
                {
                    b.HasOne("IdentityExperience.Domain.Entities.AiGenerationLog", null)
                        .WithMany()
                        .HasForeignKey("AiGenerationLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AiSuggestedTask_Log");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.ExternalLogin", b =>
                {
                    b.HasOne("IdentityExperience.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExternalLogin_User");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.OtpCode", b =>
                {
                    b.HasOne("IdentityExperience.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OtpCode_User");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("IdentityExperience.Domain.Entities.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_RefreshToken_Replaced");

                    b.HasOne("IdentityExperience.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_User");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("IdentityExperience.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Permission");

                    b.HasOne("IdentityExperience.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Role");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("IdentityExperience.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserProfile_User");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("IdentityExperience.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Role");

                    b.HasOne("IdentityExperience.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_User");
                });

            modelBuilder.Entity("IdentityExperience.Domain.Entities.UserSkill", b =>
                {
                    b.HasOne("IdentityExperience.Domain.Entities.SkillCatalog", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSkill_Skill");

                    b.HasOne("IdentityExperience.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSkill_User");
                });
#pragma warning restore 612, 618
        }
    }
}
